const elements = [
    {
    "id": 0,
    "consola": "xbox",
    "img": "./IMG/haloPort.jpg",
    "name": "Halo Infinite",
    "descripcion": "DESCRIPCION",
    "precio": "1406.48",
    "cantidad": 1,
    "video": "https://youtu.be/PyMlV5_HRWk"
    },
    {
    "id": 1,
    "consola": "xbox",
    "img": "./IMG/falloutPort.jpg",
    "name": "Fallout 4",
    "descripcion": "DESCRIPCION",
    "precio": "1136.10",
    cantidad: 1,
    },
    {
    "id": 2,
    "consola": "xbox",
    "img": "./IMG/modernWarfare.jpg",
    "name": "Modern Warfare 3",
    "descripcion": "DESCRIPCION",
    "precio": "818.02",
    cantidad: 1,
    },
    {
    "id": 3,
    "consola": "xbox",
    "img": "./IMG/halo5Port.jpg",
    "name": "Halo 5",
    "descripcion": "DESCRIPCION",
    "precio": "1051.62",
    cantidad: 1,
    },
    {
    "id": 4,
    "consola": "xbox",
    "img": "./IMG/noMansSky.webp",
    "name": "No Man's Sky",
    "descripcion": "DESCRIPCION",
    "precio": "850.15",
    cantidad: 1,
    },
    {
    "id": 5,
    "consola": "playstation",
    "img": "./IMG/bloodborne.webp",
    "name": "Bloodborne",
    "descripcion": "DESCRIPCION",
    "precio": "1422.90",
    cantidad: 1,
    },
    {
    "id": 6,
    "consola": "playstation",
    "img": "./IMG/fifaPort.jpg",
    "name": "Fifa",
    "descripcion": "DESCRIPCION",
    "precio": "1388.39",
    cantidad: 1,
    },
    {
    "id": 7,
    "consola": "playstation",
    "img": "./IMG/lastofus.webp",
    "name": "The Last of Us",
    "descripcion": "DESCRIPCION",
    "precio": "1152.68",
    cantidad: 1,
    },
    {
    "id": 8,
    "consola": "playstation",
    "img": "./IMG/horizon.jpg",
    "name": "Horizon",
    "descripcion": "DESCRIPCION",
    "precio": "1217.88",
    cantidad: 1,
    },
    {
    "id": 9,
    "consola": "playstation",
    "img": "./IMG/spiderman.avif",
    "name": "Spiderman",
    "descripcion": "DESCRIPCION",
    "precio": "1374.60",
    cantidad: 1,
    },
    {
    "id": 10,
    "consola": "nintendo",
    "img": "./IMG/mariokart.webp",
    "name": "Mario Kart Deluxe 8",
    "descripcion": "DESCRIPCION",
    "precio": "801.03",
    cantidad: 1,
    },
    {
    "id": 11,
    "consola": "nintendo",
    "img": "./IMG/smashbros.jpg",
    "name": "Super Smash Bros",
    "descripcion": "DESCRIPCION",
    "precio": "948.37",
    cantidad: 1,
    },
    {
    "id": 12,
    "consola": "nintendo",
    "img": "./IMG/zelda.jpg",
    "name": "Zelda",
    "descripcion": "DESCRIPCION",
    "precio": "1378.05",
    cantidad: 1,
    },
    {
    "id": 13,
    "consola": "nintendo",
    "img": "./IMG/pokemon.jpg",
    "name": "Pokemon",
    "descripcion": "DESCRIPCION",
    "precio": "1222.00",
    cantidad: 1,
    },
    {
    "id": 14,
    "consola": "nintendo",
    "img": "./IMG/mario.jpg",
    "name": "Super Mario 3",
    "descripcion": "DESCRIPCION",
    "precio": "1071.82",
    cantidad: 1,
    }
]
